services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # 自动注册目录服务
    Tourze\DifyWorkflowBundle\Service\:
        resource: '../../Service/'
        public: true

    # WorkflowService 的自定义参数配置
    Tourze\DifyWorkflowBundle\Service\WorkflowService:
        arguments:
            $apiClient: '@HttpClientBundle\Client\ApiClient'